endpoints:
  health:
    enabled: true
micronaut:
  server:
    port: 8082
  application:
    name: productAPISub
cassandra:
  default:
    basic:
      contact-points:
        - 192.168.100.2:9042
      session-keyspace: product
      load-balancing-policy:
        local-datacenter: datacenter1
nats.addresses:
  - nats://localhost:4222
